name: nkas_mobile
description: NKAS Mobile built with Flutter and shadcn_ui.
publish_to: 'none'
version: 1.1.1
environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  shadcn_ui: ^0.56.3
  lucide_icons_flutter: ^3.1.19
  http: ^1.6.0
  shared_preferences: 2.5.3
  web_socket_channel: ^3.0.3
  url_launcher: ^6.3.2
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/nkas.png
    - assets/licenses/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-VF.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/nkas.png"
  adaptive_icon_background: "#0D1117"
  adaptive_icon_foreground: "assets/nkas.png"
  web:
    generate: true
    image_path: "assets/nkas.png"
    background_color: "#0D1117"
    theme_color: "#0D1117"
